version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
      - PORT=8080

  frontend:
    build: ./admin-panel
    container_name: frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_UR=http://localhost:8080/api

  client:
    build: ./client
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_SERVER_PORT=http://localhost:4000/api

volumes: 
  mongodb_data:
